### ISSUE TITLE
Report name from field not updating when report is executed?

### ISSUE THREAD

**Issue by ericraskin** [mariodavid/cuba-component-scheduled-reports#2]
I have a report template defined with an output name pattern like this:  mlgresponse_${Root.file}.xlsx

My report has a Root band that contains the following Oracle SQL:

select lower(user) || '_' || to_char(sysdate,'YYYYMMDD') as "file"
from dual

When I execute the report through the regular interface, I get filenames like "mlgresponse_eraskin_20191011.xlsx".  When I execute a scheduled report through your interface, I get "mlgresponse_${Root.file}.xlsx.xlsx".  And, the report file itself is empty (although that may be a parameter issue on my part - not sure yet).

Any idea why the output path is not getting updated properly?

**Comment by ericraskin** [comment]
So, after much single-stepping, I find this code:
```
    protected FileDescriptor createAndSaveReportDocument(Report report, ReportTemplate template, Map<String, Object> params, String fileName) {
        byte[] reportData = createReportDocument(report, template, params).getContent();
        String ext = template.getReportOutputType().toString().toLowerCase();

        return saveReport(reportData, fileName, ext);
    }
```
This overrides the carefully built output file name.  I think they want to get the filename from the Report object instead and only build yours if none is supplied?  It seems I need to raise this with Haulmont as it is in their ReportingBean.java code.

**Comment by ericraskin** [comment]
FYI - I just posted this in the Cuba support forum:  [Reporting API with output name pattern not working](https://www.cuba-platform.com/discuss/t/reporting-api-with-output-name-pattern-not-working/10405)

**Comment by mariodavid** [comment]
hi,

thanks for taking a look into it. As it seems this is a bug in the reports addon: https://github.com/cuba-platform/reports/issues/223

I will close this here then.
